### ISSUE TITLE
smartthings adddevice error

### ISSUE THREAD

**Issue by infofun** [vervallsweg/smartthings#47]
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'physicalgraph.device.Device' on field 'deviceNetworkId': rejected value [B817EB42F352]; codes [physicalgraph.device.Device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.error.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique.error,device.deviceNetworkId.unique.error.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.error.deviceNetworkId,device.deviceNetworkId.unique.error.java.lang.String,device.deviceNetworkId.unique.error,physicalgraph.device.Device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.deviceNetworkId,physicalgraph.device.Device.deviceNetworkId.unique.java.lang.String,physicalgraph.device.Device.deviceNetworkId.unique,device.deviceNetworkId.unique.physicalgraph.device.Device.deviceNetworkId,device.deviceNetworkId.unique.deviceNetworkId,device.deviceNetworkId.unique.java.lang.String,device.deviceNetworkId.unique,unique.physicalgraph.device.Device.deviceNetworkId,unique.deviceNetworkId,unique.java.lang.String,unique]; arguments [deviceNetworkId,class physicalgraph.device.Device,B817EB42F352]; default message [{0} must be unique]
@line 125 (addDevices)

-------------------------------------------------------------------------

The above error is displayed.
cast-web-api version 1.0.2
smartthings cast app, dht 1.0.0

**Comment by infofun** [comment]
cast-web-service-manager.groovy

line 125 
addChildDevice("vervallsweg", "cast-web-api", ""+state.latestHttpMac, location.hubs[0].id, [

- modify

addChildDevice("vervallsweg", "cast-web-api", "cast"+state.latestHttpMac, location.hubs[0].id, [

**Comment by vervallsweg** [comment]
Changing line 125 won't fix this issue. There is a reason why the DNI is the mac address of the computer running the api.

Basically no package will make it back to ST.

Fix: Uninstall your other bridges/apis/whatever on this device or get a second device.
