### ISSUE TITLE
cast-web-device - Page crashing when entering device

### ISSUE THREAD

**Issue by JonGillibrand** [vervallsweg/smartthings#48]
Hi,
Im having an issue after a new install using the code for the DTH and SmartApp found in the guide [https://vervallsweg.github.io/cast-web/installation/. 

I have added my devices (8) using discovery but when I click on any one of them under My Devices, I just get a white page with no controls for a split second then app drops back to the Devices list.

Im using ST app v2.16.1 on Android 8.
Hope you can help.

**Comment by vervallsweg** [comment]
Is this still an issue? If so you need to enable logs in Smartthings and post them here.

**Comment by vervallsweg** [comment]
Closed due to inactivity. Feel free to reopen.
