### ISSUE TITLE
Could not find cast web

### ISSUE THREAD

**Issue by awais786327** [vervallsweg/smartthings#51]
While following this [document](https://vervallsweg.github.io/cast-web/first-steps/), i am unable to find  **cast web - service manager** mentioned in **point 2** cuz never found this option in my smartThings app so what should i suppose to do at this point ?

1. Open your SmartThings mobile app
2. Go to: 'Marketplace' > 'Smartapps' > '+ My Apps' > **Cast web - service manager**

any help appreciated thanks.

**Comment by vervallsweg** [comment]
Have you published the service manager?

If they don't show up this means you either didn't publish them or published them to the wrong location.

https://vervallsweg.github.io/cast-web/installation-service-manager-and-device-type/

**Comment by vervallsweg** [comment]
Closed due to inactivity. Feel free to reopen.
