### ISSUE TITLE
Cast-web cancels playing music

### ISSUE THREAD

**Issue by tjsnow** [vervallsweg/smartthings#52]
Currently when a message is cast to the google home speaker, it stops playing the music it was streaming from spotify. Based on the bit of rummaging around I have done, it is because it is using TTS to cast. Is there anyway to restore the previous command, or resume playing music?  Is it possible to use the broadcast command instead of TTS?

**Comment by vervallsweg** [comment]
Sorry to inform you, but this isn't possible. Only possible if you were previously casting a preset. In the future you can use the Google Assistant Broadcast feature. It should leave beta soon.
https://github.com/vervallsweg/cast-web-api/issues/91
