### ISSUE TITLE
Cast web - service manager -- Cannot create new device handler from code

### ISSUE THREAD

**Issue by shanekorbel** [vervallsweg/smartthings#54]
When trying to deploy the device handler from the code for the service manager I get the following error from the smartthings IDE: 

Groovy.lang.MissingMethodException: No signature of method: script_dth_metadata_8430a0ed_062a_419c_88ea_41660e2813a1.appSetting() is applicable for argument types: (java.lang.String) values: [api] Possible solutions: typeSetting(java.lang.String), typeSetting(java.util.Map), typeSetting(java.lang.String, java.lang.String), getSettings(), setSettings(java.lang.Object), typeSetting(java.lang.String, java.lang.String, java.util.List)

**Comment by IAmTron** [comment]
Hi it looks like i'm having the same issue:

Groovy.lang.MissingMethodException: No signature of method: script_dth_metadata_8aaf2c7d_ca42_4962_ae71_9c8dd2cea960.appSetting() is applicable for argument types: (java.lang.String) values: [api] Possible solutions: typeSetting(java.lang.String), typeSetting(java.util.Map), typeSetting(java.lang.String, java.lang.String), getSettings(), setSettings(java.lang.Object), typeSetting(java.lang.String, java.lang.String, java.util.List)

**Comment by jezzaaa** [comment]
Same here. I also get a second line that says:
`Possible solutions: typeSetting(java.lang.String), typeSetting(java.util.Map), typeSetting(java.lang.String, java.lang.String), getSettings(), setSettings(java.lang.Object), typeSetting(java.lang.String, java.lang.String, java.util.List) @line 16 (run)`
When I look at line 16, this is the definition() clause. It doesn't look right to me (although I'm no Groovy programmer) but the brackets don't seem to line up with the content. Essentially we have:
`definition(
    name: "yada",
    etc: "etc",
    iconX3Url: "https://github.com/yada/yada.png") {
    appSetting "api"
}`
It's as if definition() finishes just before appSetting and then there's a pair of braces around appSetting.

**Comment by jezzaaa** [comment]
Firstly, the structure of line 16 is fine - I just don't know enough about Groovy.

And finally, I worked out my error. I had pasted the code for cast-web-service-manager into the existing handler for cast-web-api (I was doing an upgrade). Once I copied the correct code, it saved just fine.

**Comment by vervallsweg** [comment]
> When I look at line 16, this is the definition() clause. It doesn't look right to me (although I'm no Groovy programmer) but the brackets don't seem to line up with the content.

True. This is odd. But it was [added in 2017](https://github.com/vervallsweg/smartthings/commit/453c067d6f7db28f1689c3db9c3dc1b163e0f0c3) and hasn't caused any issues so far.



> **`@line 16`**` (run)`

The issue with STs IDE is that it doesn't really clarify where this message originated. There is no `run()` method in cast-web, neither is there an `appSetting()` method.

This issue probably originated further up in STs groovy stack, which has these methods. Developing for ST I encountered some of these messages already, and they're often an indication for:

 - overloaded ST plattform
 - bugs/changes in the ST plattform
 - some other bug in the script you're trying to run

I'd recommend to remove all the code from the service manager in the ST IDE (ctrl+a, then delete) and copy and paste the code again. You can use [this link](https://raw.githubusercontent.com/vervallsweg/smartthings/master/smartapps/vervallsweg/cast-web-service-manager.src/cast-web-service-manager.groovy), which links to the raw code. Copy all, paste it in, save and publish again.

**Comment by ashzade** [comment]
I'm still getting this error. I tried adding a new device handler from scratch. I tried copying over the working cast-web-api handler and same error. Any one else?

EDIT: I'm dumb - I was adding it as a device handler, not smart app.
